### ISSUE TITLE
not able to connect to the inverter

### ISSUE THREAD

**Issue by oziee** [mletenay/home-assistant-goodwe-inverter#131]
using HA 2022.8.7
using v0.9.9.3 of this integration

when entering in the ip of the inverter I get the error 'Unknown error occurred' and in the logs I see this

```
2022-08-28 13:20:29.566 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
resp = await request_handler(request)
File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 222, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 177, in post
return await super().post(request, flow_id)
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
result = await method(view, request, data, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 109, in post
result = await self._flow_mgr.async_configure(flow_id, data)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 277, in async_configure
result = await self._async_handle_step(
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 359, in _async_handle_step
result: FlowResult = await getattr(flow, method)(user_input)
File "/config/custom_components/goodwe/config_flow.py", line 93, in async_step_user
inverter = await connect(host=host, retries=10)
File "/usr/local/lib/python3.10/site-packages/goodwe/__init__.py", line 52, in connect
return await discover(host, timeout, retries)
File "/usr/local/lib/python3.10/site-packages/goodwe/__init__.py", line 70, in discover
response = await Aa55ProtocolCommand("010200", "0182").execute(host, timeout, retries)
File "/usr/local/lib/python3.10/site-packages/goodwe/protocol.py", line 109, in execute
await response_future
File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 1017, in _read_ready
data, addr = self._sock.recvfrom(self.max_size)
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by oziee** [comment]
dam wrong inverter ip
