### ISSUE TITLE
float() argument must be a string or a real number, not 'NoneType'

### ISSUE THREAD

**Issue by oziee** [mletenay/home-assistant-goodwe-inverter#180]
my goodwe SBP inverter logs this error in the logs.. a None must be getting returned and the code is trying to convert it to a float value.. guessing some extra code IF's might be needed to prevent the error :)

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/goodwe/number.py", line 145, in async_setup_entry
    InverterNumberEntity(device_info, description, inverter, current_value)
  File "/config/custom_components/goodwe/number.py", line 168, in __init__
    self._attr_native_value = float(current_value)
TypeError: float() argument must be a string or a real number, not 'NoneType'
```

**Comment by mletenay** [comment]
Fixed in v0.9.9.11
