### ISSUE TITLE
unavailable states causing errors to log

### ISSUE THREAD

**Issue by oziee** [mletenay/home-assistant-goodwe-inverter#181]
errors are logging setting states when they are unavailable 

```
Traceback (most recent call last):
  File "/config/custom_components/goodwe/select.py", line 139, in update_eco_mode_power
    self._eco_mode_power = int(float(event.data.get("new_state").state))
ValueError: could not convert string to float: 'unavailable'
```

and 

```
Traceback (most recent call last):
  File "/config/custom_components/goodwe/select.py", line 153, in update_eco_mode_soc
    self._eco_mode_soc = int(float(event.data.get("new_state").state))
ValueError: could not convert string to float: 'unavailable'
```

**Comment by mletenay** [comment]
Fixed in acc4dbc126a102c4a0b94b8cef910e88b2d467ca , will get to next release (in couple of days)
