### ISSUE TITLE
Exception in callback async_track_point_in_utc_time

### ISSUE THREAD

**Issue by oziee** [mletenay/home-assistant-goodwe-inverter#187]
```
Logger: homeassistant
Source: custom_components/goodwe/sensor.py:243 
First occurred: 12:00:00 AM (2 occurrences) 
Last logged: 12:00:00 AM

Error doing job: Exception in callback async_track_point_in_utc_time.<locals>.run_action(<Job track po...7fcecc47ab90>>) at /usr/src/homeassistant/homeassistant/helpers/event.py:1326
Error doing job: Exception in callback async_track_point_in_utc_time.<locals>.run_action(<Job track po...7fceee0adbd0>>) at /usr/src/homeassistant/homeassistant/helpers/event.py:1326
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1341, in run_action
    hass.async_run_hass_job(job, utc_point_in_time)
  File "/usr/src/homeassistant/homeassistant/core.py", line 607, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1296, in utc_converter
    hass.async_run_hass_job(job, dt_util.as_local(utc_now))
  File "/usr/src/homeassistant/homeassistant/core.py", line 607, in async_run_hass_job
    hassjob.target(*args)
  File "/config/custom_components/goodwe/sensor.py", line 243, in async_reset
    self.coordinator.reset_sensor(self._sensor.id)
AttributeError: 'Energy' object has no attribute 'id'
```

**Comment by mletenay** [comment]
Already fixed on upstream HA, will get to next release of this experimental version
