### ISSUE TITLE
Errors after HA update to 2023.6.1

### ISSUE THREAD

**Issue by chemuki205** [mletenay/home-assistant-goodwe-inverter#198]
The Goodwe integration has stopped working in this version after giving multiple errors in the log, the integration loads on HA reboot and collects the states at that time, but does not update the data.

I have 2 inverters that until the update have worked without problems, the error seems to be related to **sensor.goodwe_pv1_mode_label**

I quote some of the errors found in the log

```
2023-06-16 11:57:05.443 DEBUG (MainThread) [goodwe.protocol] Sending: aa55c07f0106000245
2023-06-16 11:57:05.790 DEBUG (MainThread) [goodwe.protocol] Received: aa557fc001868c091a0044020a37004e020215000300500122000500020019000064006460010000010973008b171a1388010973000a08db1389010201e2000000000000d9030000273d7fe2805a000111fb0d750100300100d60001000003e3001008000000160c0d0a0f1200000000000000000000000000000000000000000000000000001ade0000112f020000000000001386
2023-06-16 11:57:05.791 DEBUG (MainThread) [custom_components._goodwe] Finished fetching GoodWe 1 (88) data in 0.348 seconds (success: True)
2023-06-16 11:57:05.793 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 583, in state
    numerical_value = float(value)  # type:ignore[arg-type]
                      ^^^^^^^^^^^^
ValueError: could not convert string to float: 'PV panels connected, producing power'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 229, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 374, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 431, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 590, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 654, in _async_write_ha_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 596, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 585, in state
    raise ValueError(
ValueError: Sensor sensor.goodwe_pv1_mode_label_2 has device class 'None', state class 'measurement' unit '' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'PV panels connected, producing power' (<class 'str'>)
2023-06-16 11:57:08.474 DEBUG (MainThread) [goodwe.protocol] Sending: aa55c07f0106000245
2023-06-16 11:57:08.873 DEBUG (MainThread) [goodwe.protocol] Received: aa557fc001868c0a37004e020933004202021300030050012c00050005001900006400645d010000010974008a173f1389010974000209cd138a010201de00000000000135dc000040b48fc898eb000222040d720100300100000001000003e3000008000000160b02113913000000000000000000000000000000000000000000000000000035d2000026490200000000000013af
2023-06-16 11:57:08.874 DEBUG (MainThread) [custom_components._goodwe] Finished fetching GoodWe 2 (99) data in 0.400 seconds (success: True)
2023-06-16 11:57:08.881 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 583, in state
    numerical_value = float(value)  # type:ignore[arg-type]
                      ^^^^^^^^^^^^
ValueError: could not convert string to float: 'PV panels connected, producing power'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 229, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 374, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 431, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 590, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 654, in _async_write_ha_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 596, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 585, in state
    raise ValueError(
ValueError: Sensor sensor.goodwe_pv1_mode_label has device class 'None', state class 'measurement' unit '' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'PV panels connected, producing power' (<class 'str'>)

```

**Comment by chemuki205** [comment]
Update:

I have installed version 0.9.9.11 (I had 0.9.9.9) and now it works correctly.

**Comment by chemuki205** [comment]
Update:

I have installed version 0.9.9.11 (I had 0.9.9.9) and now it works correctly.
