### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by hans6910** [mletenay/home-assistant-goodwe-inverter#81]
I installed the new update for my Goodwe 2500xs. I also have the sems scraper component in hacs.
Sems scraper works fine, but since the new integration configuration on UDP connecting to my Goodwe it failed to connect. I use integrations, add integration, choose goodwe inverter, fill in the IP adres on local network (i can ping this adress for response, static IP on convertor).
I edited yaml and removed old goodwe platform code, i put it back in... nothing works. Still fails to connect. Checked IP in local networks...

What to do?

**Comment by mletenay** [comment]
Hmm, that's odd. I assume it was working before ?
Can you try to install some older version ? (In HACS do reinstall and select e.g. v0.9.0 and put back the yaml config).
Just to identify what is wrong

**Comment by hans6910** [comment]
Thnx! Quick reply. Haven’t noticed before, but 0.9 doesn’t connect either:

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:268 
Integration: Sensor (documentation, issues) 
First occurred: 19:13:25 (1 occurrences) 
Last logged: 19:13:25

Platform goodwe not ready yet: Unable to connect to the inverter at host=192.168.178.115, or your inverter is not supported yet. Failures=[MaxRetriesException(), MaxRetriesException(), MaxRetriesException(), MaxRetriesException()]; Retrying in background in 30 seconds

This is in the log…
It might be in UDP Port setup? Or?

Right now it’s dark… I think It switches off since I cannot ping It either…

Met vriendelijke groet,
Hans van Gerrevink

**Comment by mletenay** [comment]
Which version was the last one working ?

**Comment by mletenay** [comment]
Can you connect to the inverter with the SolarGo mobile app ?

**Comment by ppoetsma** [comment]
Maybe this helps: Today I noticed that no data was retrieved anymore (GW1500-XS). I missed the configuration change per 0.9.2 from Yaml to HA. So I removed the Yaml configuration and added the _GoodWe Inverter_ integration. Specified the IP address and data comes back in.

**Comment by rudolphi** [comment]
> I recently dis this also… unfortunately without the success you seem to have. Tried the SolarGo app. Converter is found, but there is no connection possible (It says incompatible with SolarGo). Even not when I’m on direct WiFi with the converter. In that case i can however login to the converter. We’ll try further… Met vriendelijke groet, Hans van Gerrevink

I have the same problem with our new GW10KN-ET, but connecting via Bluetooth works. The HA error log says 
`Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 181, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 296, in async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 392, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/goodwe/config_flow.py", line 36, in async_step_user
    inverter = await connect(host=host, retries=10)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/goodwe/__init__.py", line 52, in connect
    return await discover(host, timeout, retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/goodwe/__init__.py", line 70, in discover
    response = await DISCOVERY_COMMAND.execute(host, timeout, retries)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/goodwe/protocol.py", line 109, in execute
    await response_future
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 1153, in _read_ready
    data, addr = self._sock.recvfrom(self.max_size)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionRefusedError: [Errno 111] Connection refused`

but from the console of the Raspi I can connect:
`curl [IP]`
gives 401 response code. Any ideas?

Thanks very much!

Felix
